def main(x):
    match x[1]:
        case 1970:
            match x[3]:
                case 'MQL5':
                    match x[0]:
                        case 2019:
                            return 0
                        case 2015:
                            return 1
                        case 1997:
                            return 2
                case 'LSL':
                    match x[0]:
                        case 2019:
                            return 3
                        case 2015:
                            return 4
                        case 1997:
                            return 5
        case 1985:
            match x[3]:
                case 'MQL5':
                    return 6
                case 'LSL':
                    match x[2]:
                        case 'C++':
                            return 7
                        case 'WISP':
                            return 8
                        case 'BISON':
                            return 9
